services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.6.15
    #image: ghcr.io/ten-framework/ten_agent_build:0.6.15
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
      - ../.vscode/:/app/.vscode
      - ../tools/pylint/.pylintrc:/tools/pylint/.pylintrc
      - ../tools/upgrade:/tools/upgrade
    working_dir: /app
    env_file:
      - .env
    network_mode: host
  ten_agent_playground:
    image: ghcr.io/ten-framework/ten_agent_playground:0.10.31-25-g85c777953
    container_name: ten_agent_playground
    restart: always
    ports:
      - "3000:3000"
    network_mode: host
    environment:
      - AGENT_SERVER_URL=http://localhost:8080
      - TEN_DEV_SERVER_URL=http://localhost:49483
  ten_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.10.36-7-gbd11efef5
    container_name: ten_agent_demo
    restart: always
    ports:
      - "3002:3000"
    network_mode: host
    environment:
      - AGENT_SERVER_URL=http://localhost:8080
  # ten_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: ten_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - host
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
