version: "3"

dotenv: ["/app/.env"]

tasks:
  install-frontend:
    desc: install frontend dependencies
    internal: true
    dir: ./frontend
    cmds:
      - npm install --verbose

  install-tenapp:
    desc: install tenapp dependencies
    internal: true
    dir: ./tenapp
    cmds:
      - tman install

  install-tenapp-python-deps:
    desc: install tenapp python dependencies
    internal: true
    dir: ./tenapp
    cmds:
      - ./scripts/install_python_deps.sh

  build-api-server:
    desc: build api server
    dir: /app/server
    cmds:
      - go mod tidy && go mod download && go build -o bin/api main.go

  install:
    desc: install dependencies
    dir: ./tenapp
    cmds:
      - task: install-tenapp
      - task: install-tenapp-python-deps
      - task: install-frontend
      - task: build-api-server

  run-tenapp:
    desc: run tenapp
    dir: ./tenapp
    cmds:
      - tman run start

  run-gd-server:
    desc: run tman dev http server for TMAN Designer
    dir: ./tenapp
    cmds:
      - tman designer

  run-frontend:
    desc: run frontend
    dir: ./frontend
    cmds:
      - npm run dev

  run-api-server:
    desc: run api server
    dir: /app/server
    cmds:
      - ./bin/api -tenapp_dir={{.PWD}}/tenapp

  run:
    desc: run everything
    deps:
      - task: run-gd-server
      - task: run-frontend
      - task: run-api-server