name: Agents CI

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/agents.yaml"
      - ".vscode/**"
      - "**.md"
      - "agent_solutions/docs/**"
      - "agent_solutions/esp32-client/**"
      - "agent_solutions/Dockerfile"
      - "agent_solutions/docker-compose.yml"
      - "agent_solutions/demo/**"
      - "agent_solutions/playground/**"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ten-framework/ten_agent_build:0.6.1
    strategy:
      matrix:
        agent:
          [
            agents/examples/default,
            agents/examples/demo,
            agents/examples/experimental,
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          submodules: "true"

      - name: Use agent
        run: |
          git config --global --add safe.directory $(pwd)
          cd agent_solutions
          task use AGENT=${{ matrix.agent }}

      - name: Run format check
        run: |
          cd agent_solutions
          task check

      - name: Run lint
        run: |
          cd agent_solutions
          task lint

      - name: Run tests
        run: |
          cd agent_solutions
          task test -- -s -v
