name: Build Docker Image for AI Agents

on:
  push:
    branches: ["**"]
    tags: ["**"]
    paths-ignore:
      - "core/**"
      - "tests/**"
      - "tools/**"
      - "packages/**"
      - "build/**"
      - "third_party/**"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/build_docker_for_ai_agents.yml"
      - ".vscode/**"
      - "ai_agents/docs/**"
      - "**.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "core/**"
      - "tests/**"
      - "tools/**"
      - "packages/**"
      - "build/**"
      - "third_party/**"
      - ".vscode/**"
      - ".devcontainer/**"
      - ".github/**"
      - "!.github/workflows/build_docker_for_ai_agents.yml"
      - ".vscode/**"
      - "ai_agents/docs/**"
      - "**.md"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

concurrency:
  group: build-docker-for-ai-agents-${{ github.head_ref }}
  cancel-in-progress: true

env:
  SERVER_IMAGE_NAME: ten_agent_server
  PLAYGROUND_IMAGE_NAME: ten_agent_playground
  NON_EDIT_PLAYGROUND_IMAGE_NAME: ten_agent_non_edit_playground
  DEMO_IMAGE_NAME: ten_agent_demo
  TEN_EXAMPLE_DEMO_IMAGE_NAME: ten_agent_example_demo
  TEN_EXAMPLE_VOICE_ASSISTANT_IMAGE_NAME: ten_agent_example_voice_assistant

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: "0"

      - id: pre-step
        shell: bash
        run: echo "image-tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build & Publish Docker Image for examples/demo Agent
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository_owner }}/${{ env.TEN_EXAMPLE_DEMO_IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./agents/examples/demo/Dockerfile
          registry: ghcr.io
          workdir: ./ai_agents/
          tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}${{ steps.pre-step.outputs.image-tag }}"
          no_push: ${{ github.event_name == 'pull_request' }}

      - name: Build & Publish Docker Image for examples/voice-assistant Agent
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository_owner }}/${{ env.TEN_EXAMPLE_VOICE_ASSISTANT_IMAGE_NAME }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./agents/examples/voice-assistant/Dockerfile
          registry: ghcr.io
          workdir: ./ai_agents/
          tags: "${{ github.ref == 'refs/heads/main' && 'latest,' || '' }}${{ steps.pre-step.outputs.image-tag }}"
          no_push: ${{ github.event_name == 'pull_request' }}
